# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-04 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_auto_20180830_1340'),
        ('budget', '0002_auto_20180830_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changeField', models.CharField(default='None', max_length=255)),
                ('changedFrom', models.CharField(default='None', max_length=255)),
                ('changedTo', models.CharField(default='None', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='cm1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.Member'),
        ),
        migrations.AddField(
            model_name='clientchanges',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.Client'),
        ),
    ]
