# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-05 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_auto_20180830_1340'),
        ('budget', '0004_auto_20180904_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='amb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amb', to='user_management.Member'),
        ),
        migrations.AddField(
            model_name='client',
            name='cmb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmb', to='user_management.Member'),
        ),
        migrations.AddField(
            model_name='client',
            name='seob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seob', to='user_management.Member'),
        ),
        migrations.AddField(
            model_name='client',
            name='stratb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stratb', to='user_management.Member'),
        ),
    ]
