# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-06 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_auto_20180906_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientchanges',
            name='dateTime',
            field=models.DateTimeField(null=True),
        ),
    ]
