# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-06 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_auto_20180906_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientchanges',
            name='dateTime',
        ),
    ]
