# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-17 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0018_skillhistory'),
        ('client_area', '0005_clienttype_industry_language'),
        ('budget', '0008_remove_clientchanges_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='am1',
        ),
        migrations.RemoveField(
            model_name='client',
            name='am2',
        ),
        migrations.RemoveField(
            model_name='client',
            name='am3',
        ),
        migrations.RemoveField(
            model_name='client',
            name='amb',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cm1',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cm2',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cm3',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cmb',
        ),
        migrations.RemoveField(
            model_name='client',
            name='seo1',
        ),
        migrations.RemoveField(
            model_name='client',
            name='seo2',
        ),
        migrations.RemoveField(
            model_name='client',
            name='seo3',
        ),
        migrations.RemoveField(
            model_name='client',
            name='seob',
        ),
        migrations.RemoveField(
            model_name='client',
            name='strat1',
        ),
        migrations.RemoveField(
            model_name='client',
            name='strat2',
        ),
        migrations.RemoveField(
            model_name='client',
            name='strat3',
        ),
        migrations.RemoveField(
            model_name='client',
            name='stratb',
        ),
        migrations.AddField(
            model_name='client',
            name='clientGrade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='clientType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_type', to='client_area.ClientType'),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='industry', to='client_area.Industry'),
        ),
        migrations.AddField(
            model_name='client',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language', to='client_area.Language'),
        ),
        migrations.AddField(
            model_name='client',
            name='mainContact',
            field=models.EmailField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='services', to='client_area.Service'),
        ),
        migrations.AddField(
            model_name='client',
            name='soldBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sold_by', to='user_management.Member'),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='tier',
            field=models.IntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='client',
            name='team',
        ),
        migrations.AddField(
            model_name='client',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='team', to='user_management.Team'),
        ),
    ]
