# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-18 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0006_clientcontact'),
        ('budget', '0009_auto_20180917_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='mainContact',
        ),
        migrations.AddField(
            model_name='client',
            name='contactInfo',
            field=models.ManyToManyField(related_name='client_contact', to='client_area.ClientContact'),
        ),
        migrations.RemoveField(
            model_name='client',
            name='language',
        ),
        migrations.AddField(
            model_name='client',
            name='language',
            field=models.ManyToManyField(related_name='language', to='client_area.Language'),
        ),
    ]
