# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-18 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0018_skillhistory'),
        ('budget', '0010_auto_20180918_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='am1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='am1', to='user_management.Member'),
        ),
        migrations.AddField(
            model_name='client',
            name='am2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='am2', to='user_management.Member'),
        ),
        migrations.AddField(
            model_name='client',
            name='am3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='am3', to='user_management.Member'),
        ),
        migrations.AddField(
            model_name='client',
            name='amb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amb', to='user_management.Member'),
        ),
        migrations.AddField(
            model_name='client',
            name='cm1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cm1', to='user_management.Member'),
        ),
        migrations.AddField(
            model_name='client',
            name='cm2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cm2', to='user_management.Member'),
        ),
        migrations.AddField(
            model_name='client',
            name='cm3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cm3', to='user_management.Member'),
        ),
        migrations.AddField(
            model_name='client',
            name='cmb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmb', to='user_management.Member'),
        ),
        migrations.AddField(
            model_name='client',
            name='seo1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo1', to='user_management.Member'),
        ),
        migrations.AddField(
            model_name='client',
            name='seo2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo2', to='user_management.Member'),
        ),
        migrations.AddField(
            model_name='client',
            name='seo3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo3', to='user_management.Member'),
        ),
        migrations.AddField(
            model_name='client',
            name='seob',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seob', to='user_management.Member'),
        ),
        migrations.AddField(
            model_name='client',
            name='strat1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strat1', to='user_management.Member'),
        ),
        migrations.AddField(
            model_name='client',
            name='strat2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strat2', to='user_management.Member'),
        ),
        migrations.AddField(
            model_name='client',
            name='strat3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strat3', to='user_management.Member'),
        ),
        migrations.AddField(
            model_name='client',
            name='stratb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stratb', to='user_management.Member'),
        ),
    ]
