# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-20 12:33
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_auto_20180918_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='networks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='client',
            name='aw_current_ds',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='aw_projected',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='aw_rec_ds',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='aw_yesterday',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='bing_current_ds',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='bing_projected',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='bing_rec_ds',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='bing_yesterday',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='fb_current_ds',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='fb_projected',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='fb_rec_ds',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='fb_yesterday',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='clientcdata',
            name='global_target_spend',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
