# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-24 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0013_auto_20180920_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('0', 'Onboarding'), ('1', 'Soft Launch'), ('2', 'Active'), ('3', 'Inactive'), ('4', 'Lost')], default='0', max_length=9),
        ),
    ]
