# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-25 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0015_auto_20180925_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.IntegerField(choices=[(0, 'Onboarding'), (1, 'Soft Launch'), (2, 'Active'), (3, 'Inactive'), (4, 'Lost')], default=0),
        ),
    ]
