# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-26 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0012_managementfeeinterval_managementfeesstructure'),
        ('budget', '0016_auto_20180925_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cro_hourly_fee',
            field=models.FloatField(default=125),
        ),
        migrations.AddField(
            model_name='client',
            name='cro_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='has_cro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='has_seo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='managementFee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client_area.ManagementFeesStructure'),
        ),
        migrations.AddField(
            model_name='client',
            name='parentClient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client_area.ParentClient'),
        ),
        migrations.AddField(
            model_name='client',
            name='seo_hourly_fee',
            field=models.FloatField(default=125),
        ),
        migrations.AddField(
            model_name='client',
            name='seo_hours',
            field=models.FloatField(default=0),
        ),
    ]
