# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-26 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0017_auto_20180926_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
