# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-26 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0018_client_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='parentClient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_area.ParentClient'),
        ),
    ]
