# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-02 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0020_auto_20180927_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='currency',
            field=models.CharField(default='', max_length=255),
        ),
    ]
