# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-02 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0021_client_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='team',
            field=models.ManyToManyField(blank=True, null=True, related_name='team', to='user_management.Team'),
        ),
    ]
