# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-02 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0022_auto_20181002_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='global_budget',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='other_budget',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='team', to='user_management.Team'),
        ),
    ]
