# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-03 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0023_auto_20181002_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='payment_schedule',
            field=models.IntegerField(choices=[(0, 'MRR'), (1, 'One Time')], default=0),
        ),
    ]
