# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-03 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0025_auto_20181003_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='management_fee_override',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='allocated_ppc_override',
            field=models.FloatField(default=None, null=True),
        ),
    ]
