# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-09 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0028_auto_20181009_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='global_budget',
            new_name='flex_budget',
        ),
    ]
