# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-11 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0029_auto_20181009_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='projection_method',
            field=models.IntegerField(choices=[(0, 'Yesterday'), (1, 'Monthly Average')], default=0),
        ),
    ]
