# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-29 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0035_client_star_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigngrouping',
            name='group_by_contains',
            field=models.BooleanField(default=True),
        ),
    ]
