# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-31 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0036_campaigngrouping_group_by_contains'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='flex_budget_end_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='flex_budget_start_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
