# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-07 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0037_auto_20181031_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBudgetSpendHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('aw_budget', models.FloatField(default=0)),
                ('bing_budget', models.FloatField(default=0)),
                ('fb_budget', models.FloatField(default=0)),
                ('flex_budget', models.FloatField(default=0)),
                ('aw_spend', models.FloatField(default=0)),
                ('bing_spend', models.FloatField(default=0)),
                ('fb_spend', models.FloatField(default=0)),
                ('flex_spend', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='campaigngrouping',
            name='group_by_contains',
        ),
        migrations.AlterField(
            model_name='client',
            name='flex_budget_end_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='flex_budget_start_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='accountbudgetspendhistory',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.Client'),
        ),
    ]
