# Generated by Django 2.1.1 on 2018-11-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0040_auto_20181112_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='target_cpa',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='target_roas',
            field=models.FloatField(default=0),
        ),
    ]
