# Generated by Django 2.1.1 on 2018-11-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0041_auto_20181121_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbudgetspendhistory',
            name='management_fee',
            field=models.FloatField(default=0.0),
        ),
    ]
