# Generated by Django 2.1.1 on 2018-12-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0042_accountbudgetspendhistory_management_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tier_override',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
