# Generated by Django 2.1.1 on 2018-12-03 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0024_auto_20181112_1559'),
        ('budget', '0043_client_tier_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='TierChangeProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_from', models.IntegerField(default=0)),
                ('tier_to', models.IntegerField(default=0)),
                ('fee_from', models.FloatField(default=0.0)),
                ('fee_to', models.FloatField(default=0.0)),
                ('changed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='budget.Client')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_management.Member')),
            ],
        ),
    ]
