# Generated by Django 2.1.1 on 2018-12-03 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0044_tierchangeproposal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='tier_override',
        ),
    ]
