# Generated by Django 2.1.1 on 2018-12-04 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0045_remove_client_tier_override'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='clientType',
        ),
        migrations.AlterField(
            model_name='tierchangeproposal',
            name='account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='budget.Client'),
        ),
        migrations.AlterField(
            model_name='tierchangeproposal',
            name='changed_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_management.Member'),
        ),
    ]
