# Generated by Django 2.1.1 on 2018-12-14 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0029_traininghoursrecord'),
        ('budget', '0046_auto_20181204_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='flagged_assigned_member',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='flagged_assigned_member', to='user_management.Member'),
        ),
        migrations.AddField(
            model_name='client',
            name='flagged_bc_link',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='flagged_datetime',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
