# Generated by Django 2.1.1 on 2019-01-07 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0049_auto_20190104_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='amb',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cmb',
        ),
        migrations.RemoveField(
            model_name='client',
            name='seob',
        ),
        migrations.RemoveField(
            model_name='client',
            name='stratb',
        ),
    ]
