# Generated by Django 2.1.1 on 2019-01-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0050_auto_20190107_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='objective',
            field=models.IntegerField(choices=[(0, 'Leads'), (1, 'Sales'), (2, 'Awareness'), (3, 'Store Visits'), (4, 'Multiple')], default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='sold_budget',
            field=models.FloatField(default=0.0),
        ),
    ]
