# Generated by Django 2.1.1 on 2019-01-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0054_auto_20190121_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='late_onboard_reason',
            field=models.CharField(blank=True, default=None, max_length=140, null=True),
        ),
    ]
