# Generated by Django 2.1.1 on 2019-01-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0055_client_late_onboard_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phase',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three')], default=1),
        ),
        migrations.AddField(
            model_name='client',
            name='phase_day',
            field=models.IntegerField(default=0),
        ),
    ]
