# Generated by Django 2.1.1 on 2019-01-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0056_auto_20190128_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ninety_day_cycle',
            field=models.IntegerField(default=1),
        ),
    ]
