# Generated by Django 2.1.1 on 2019-02-05 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0032_auto_20190104_0950'),
        ('budget', '0057_client_ninety_day_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='team_lead_override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tl_override', to='user_management.Member'),
        ),
    ]
