# Generated by Django 2.1.1 on 2019-02-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0058_client_team_lead_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='budget_updated',
            field=models.BooleanField(default=False),
        ),
    ]
