# Generated by Django 2.1.1 on 2019-03-21 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0059_client_budget_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='services',
        ),
    ]
