# Generated by Django 2.1.1 on 2019-03-22 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0060_remove_client_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='has_cro',
        ),
        migrations.RemoveField(
            model_name='client',
            name='has_ppc',
        ),
        migrations.RemoveField(
            model_name='client',
            name='has_seo',
        ),
        migrations.RemoveField(
            model_name='client',
            name='has_strat',
        ),
    ]
