# Generated by Django 2.1.1 on 2019-03-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0061_auto_20190322_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigngrouping',
            name='group_type',
            field=models.IntegerField(choices=[(0, 'all'), (1, 'manual'), (2, 'text')], default=0),
        ),
    ]
