# Generated by Django 2.1.1 on 2019-03-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0062_campaigngrouping_group_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigngrouping',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='campaigngrouping',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='adwords',
            field=models.ManyToManyField(blank=True, to='adwords_dashboard.DependentAccount'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bing',
            field=models.ManyToManyField(blank=True, to='bing_dashboard.BingAccounts'),
        ),
        migrations.AlterField(
            model_name='client',
            name='facebook',
            field=models.ManyToManyField(blank=True, to='facebook_dashboard.FacebookAccount'),
        ),
    ]
