# Generated by Django 2.1.1 on 2019-06-03 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0063_auto_20190329_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='other_budget',
        ),
    ]
