# Generated by Django 2.1.1 on 2019-06-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0064_remove_client_other_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbudgetspendhistory',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
