# Generated by Django 2.1.1 on 2019-06-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0065_accountbudgetspendhistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='override_difference',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
