# Generated by Django 2.1.1 on 2019-06-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0066_client_override_difference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='override_difference',
        ),
    ]
