# Generated by Django 2.1.1 on 2019-06-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0067_remove_client_override_difference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='adwords',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
