# Generated by Django 2.1.1 on 2019-06-19 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0068_auto_20190619_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightbudget',
            name='adwords_account',
        ),
        migrations.RemoveField(
            model_name='flightbudget',
            name='bing_account',
        ),
        migrations.RemoveField(
            model_name='flightbudget',
            name='facebook_account',
        ),
        migrations.DeleteModel(
            name='FlightBudget',
        ),
    ]
