# Generated by Django 2.1.1 on 2019-06-19 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0069_auto_20190619_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_monthly', models.BooleanField(default=True)),
                ('has_adwords', models.BooleanField(default=False)),
                ('has_facebook', models.BooleanField(default=False)),
                ('has_bing', models.BooleanField(default=False)),
                ('grouping_type', models.IntegerField(choices=[(0, 'manual'), (1, 'text'), (2, 'all')], default=2)),
                ('text_includes', models.CharField(max_length=999)),
                ('text_excludes', models.CharField(max_length=999)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_account', to='budget.Client')),
            ],
        ),
    ]
