# Generated by Django 2.1.1 on 2019-06-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0072_auto_20190620_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='end_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='start_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
