# Generated by Django 2.1.1 on 2019-06-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0074_budget_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='grouping_type',
            field=models.IntegerField(choices=[(0, 'manual'), (1, 'text strings'), (2, 'all campaigns')], default=2),
        ),
    ]
