# Generated by Django 2.1.1 on 2019-06-26 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adwords_dashboard', '0020_auto_20190626_0806'),
        ('facebook_dashboard', '0014_auto_20190626_0806'),
        ('bing_dashboard', '0014_auto_20190626_0806'),
        ('budget', '0075_auto_20190625_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignExclusions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.Client')),
                ('aw_campaigns', models.ManyToManyField(to='adwords_dashboard.Campaign')),
                ('bing_campaigns', models.ManyToManyField(to='bing_dashboard.BingCampaign')),
                ('fb_campaigns', models.ManyToManyField(to='facebook_dashboard.FacebookCampaign')),
            ],
        ),
    ]
