# Generated by Django 2.1.1 on 2019-06-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0076_campaignexclusions'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
