# Generated by Django 2.1.1 on 2019-07-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0077_budget_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bc_link',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
