# Generated by Django 2.1.1 on 2019-07-23 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0078_auto_20190709_0652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['name']},
        ),
    ]
