# Generated by Django 2.1.1 on 2019-07-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0079_client_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
