# Generated by Django 2.1.1 on 2019-07-29 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0080_additionalfee'),
        ('budget', '0080_client_notes'),
    ]

    operations = [
    ]
