# Generated by Django 2.1.1 on 2019-08-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0083_budgetupdate_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='needs_renewing',
            field=models.BooleanField(default=False),
        ),
    ]
