# Generated by Django 2.1.1 on 2019-08-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0086_auto_20190805_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.IntegerField(choices=[(0, 'Onboarding'), (1, 'Active'), (2, 'Inactive'), (3, 'Lost')], default=0),
        ),
    ]
