# Generated by Django 2.1.1 on 2019-08-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0087_auto_20190805_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='inactive_reason',
            field=models.IntegerField(choices=[(0, 'PO pending from client'), (1, 'Website being worked on'), (2, 'New budget pending from client'), (3, 'Late onboarding'), (4, 'Other')], default=None, null=True),
        ),
    ]
