# Generated by Django 2.1.1 on 2019-08-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0089_auto_20190807_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
