# Generated by Django 2.1.1 on 2019-08-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0091_auto_20190815_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='onboarding_hours_allocated_updated_timestamp',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
