# Generated by Django 2.1.1 on 2019-08-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0090_auto_20190822_1335'),
        ('budget', '0091_auto_20190815_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tags',
            field=models.ManyToManyField(blank=True, to='client_area.Tag'),
        ),
    ]
