# Generated by Django 2.1.1 on 2019-08-27 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0092_client_tags'),
        ('budget', '0093_client_onboarding_hours_allocated_this_month_field'),
    ]

    operations = [
    ]
