# Generated by Django 2.1.1 on 2019-10-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0095_auto_20191010_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='num_days_onboarding',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
