# Generated by Django 2.1.1 on 2019-10-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0095_auto_20191007_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
