# Generated by Django 2.1.1 on 2019-10-16 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0096_auto_20191010_1243'),
        ('budget', '0096_budget_is_edited'),
    ]

    operations = [
    ]
