# Generated by Django 2.1.1 on 2019-11-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0097_merge_20191016_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='region',
            field=models.IntegerField(choices=[(1, 'QC'), (2, 'ON'), (3, 'US'), (4, 'BC'), (5, 'AB'), (6, 'SK')], default=1),
        ),
    ]
