# Generated by Django 2.1.1 on 2019-11-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0098_client_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_active_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
