# Generated by Django 2.1.1 on 2019-11-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0099_client_last_active_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='last_active_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='num_days_onboarding',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
