# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-27 16:20
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=355)),
                ('account_name', models.CharField(default='None', max_length=255)),
                ('desired_spend', models.IntegerField(default=0)),
                ('current_spend', models.FloatField(default=0)),
                ('segmented_spend', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('channel', models.CharField(default='None', max_length=255)),
                ('trends', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('hist_spend', models.FloatField(default=0)),
                ('hist_budget', models.FloatField(default=0)),
                ('ds1', models.IntegerField(default=0)),
                ('ds2', models.IntegerField(default=0)),
                ('ds3', models.IntegerField(default=0)),
                ('ds4', models.IntegerField(default=0)),
                ('ds5', models.IntegerField(default=0)),
                ('ds6', models.IntegerField(default=0)),
                ('yesterday_spend', models.FloatField(default=0)),
                ('estimated_spend', models.FloatField(default=0)),
                ('quality_score', models.IntegerField(default=0)),
                ('dads_score', models.FloatField(default=0)),
                ('trends_score', models.FloatField(default=0)),
                ('historical_qs', models.IntegerField(default=0)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('assigned', models.BooleanField(default=False)),
                ('blacklisted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('assigned_am', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fb_am', to=settings.AUTH_USER_MODEL)),
                ('assigned_cm2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fb_cm2', to=settings.AUTH_USER_MODEL)),
                ('assigned_cm3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fb_cm3', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_time', 'updated_time'],
            },
        ),
        migrations.CreateModel(
            name='FacebookAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=255)),
                ('alert_reason', models.CharField(max_length=255)),
                ('ad_id', models.CharField(max_length=255)),
                ('ad_name', models.CharField(max_length=255)),
                ('adset_id', models.CharField(default='None', max_length=255)),
                ('adset_name', models.CharField(default='None', max_length=255)),
                ('campaign_id', models.CharField(default='None', max_length=255)),
                ('campaign_name', models.CharField(default='None', max_length=255)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook_dashboard.FacebookAccount')),
            ],
            options={
                'ordering': ['created_time', 'updated_time'],
            },
        ),
        migrations.CreateModel(
            name='FacebookCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(default='None', max_length=255)),
                ('campaign_name', models.CharField(default='None', max_length=455)),
                ('campaign_cost', models.FloatField(default=0)),
                ('campaign_budget', models.FloatField(default=0)),
                ('groupped', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook_dashboard.FacebookAccount')),
            ],
        ),
        migrations.CreateModel(
            name='FacebookPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_type', models.CharField(max_length=255)),
                ('campaign_id', models.CharField(default='None', max_length=255)),
                ('campaign_name', models.CharField(default='None', max_length=255)),
                ('cpc', models.CharField(max_length=255)),
                ('clicks', models.CharField(max_length=255)),
                ('conversions', models.CharField(max_length=255)),
                ('cost', models.CharField(default=0, max_length=255)),
                ('cost_per_conversions', models.CharField(max_length=255)),
                ('ctr', models.CharField(max_length=255)),
                ('impressions', models.CharField(max_length=255)),
                ('search_impr_share', models.CharField(max_length=255)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook_dashboard.FacebookAccount')),
            ],
            options={
                'ordering': ['created_time', 'updated_time'],
            },
        ),
    ]
