# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-25 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookcampaign',
            name='campaign_yesterday_cost',
            field=models.FloatField(default=0),
        ),
    ]
