# Generated by Django 2.1.1 on 2018-11-12 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_dashboard', '0004_auto_20181107_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookaccount',
            name='assigned_am',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fb_am', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facebookaccount',
            name='assigned_cm2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fb_cm2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facebookaccount',
            name='assigned_cm3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fb_cm3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facebookaccount',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facebookalert',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='facebook_dashboard.FacebookAccount'),
        ),
        migrations.AlterField(
            model_name='facebookcampaign',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='facebook_dashboard.FacebookAccount'),
        ),
        migrations.AlterField(
            model_name='facebookperformance',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='facebook_dashboard.FacebookAccount'),
        ),
    ]
