# Generated by Django 2.1.1 on 2019-06-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_dashboard', '0006_auto_20190104_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookcampaign',
            name='master_exclusion',
            field=models.BooleanField(default=False),
        ),
    ]
