# Generated by Django 2.1.1 on 2019-06-25 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_dashboard', '0008_facebookcampaignspenddaterange'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookCampaignExclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facebook_dashboard.FacebookCampaign')),
            ],
        ),
    ]
