# Generated by Django 2.1.1 on 2019-06-25 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_dashboard', '0011_facebookcampaignspenddaterange_spend_until_yesterday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookalert',
            name='account',
        ),
        migrations.DeleteModel(
            name='FacebookAlert',
        ),
    ]
