# Generated by Django 2.1.1 on 2019-06-25 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_dashboard', '0012_auto_20190625_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookperformance',
            name='account',
        ),
        migrations.DeleteModel(
            name='FacebookPerformance',
        ),
    ]
