# Generated by Django 2.1.1 on 2019-06-26 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_dashboard', '0013_auto_20190625_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookcampaignexclusion',
            name='campaign',
        ),
        migrations.DeleteModel(
            name='FacebookCampaignExclusion',
        ),
    ]
