# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-27 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_management.Team'),
        ),
    ]
