# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-28 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_auto_20180828_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='members',
        ),
        migrations.AddField(
            model_name='incident',
            name='members',
            field=models.ManyToManyField(default=None, to='user_management.Member'),
        ),
    ]
