# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-30 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_auto_20180830_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.Role'),
        ),
        migrations.AlterField(
            model_name='member',
            name='team',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.Team'),
        ),
    ]
