# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-06 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_auto_20180906_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='member_team', to='user_management.Team'),
        ),
    ]
