# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-06 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_auto_20180906_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='last_language_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_skill_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
