# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-11 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_auto_20180906_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('score0', models.ManyToManyField(default=None, related_name='score0', to='user_management.Member')),
                ('score1', models.ManyToManyField(default=None, related_name='score1', to='user_management.Member')),
                ('score2', models.ManyToManyField(default=None, related_name='score2', to='user_management.Member')),
                ('score3', models.ManyToManyField(default=None, related_name='score3', to='user_management.Member')),
            ],
        ),
    ]
