# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-13 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0016_auto_20180913_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='skill_adwords',
        ),
        migrations.RemoveField(
            model_name='member',
            name='skill_bing',
        ),
        migrations.RemoveField(
            model_name='member',
            name='skill_communication',
        ),
        migrations.RemoveField(
            model_name='member',
            name='skill_confident',
        ),
        migrations.RemoveField(
            model_name='member',
            name='skill_cro',
        ),
        migrations.RemoveField(
            model_name='member',
            name='skill_english',
        ),
        migrations.RemoveField(
            model_name='member',
            name='skill_fb',
        ),
        migrations.RemoveField(
            model_name='member',
            name='skill_french',
        ),
        migrations.RemoveField(
            model_name='member',
            name='skill_linkedin',
        ),
        migrations.RemoveField(
            model_name='member',
            name='skill_pinterest',
        ),
        migrations.RemoveField(
            model_name='member',
            name='skill_seo',
        ),
        migrations.RemoveField(
            model_name='member',
            name='skill_technical',
        ),
        migrations.RemoveField(
            model_name='member',
            name='skill_twitter',
        ),
    ]
