# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-24 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0018_skillhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='last_language_check',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_skill_check',
        ),
    ]
