# Generated by Django 2.1.1 on 2018-11-12 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0022_auto_20181001_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='member',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_management.Member'),
        ),
        migrations.AlterField(
            model_name='role',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_management.RoleGroup'),
        ),
    ]
