# Generated by Django 2.1.1 on 2018-12-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0025_auto_20181204_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='backup',
            name='bc_link',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
