# Generated by Django 2.1.1 on 2018-12-06 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0027_auto_20181205_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='approved_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='backup',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approved_by', to='user_management.Member'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='backup_member', to='user_management.Member'),
        ),
    ]
