# Generated by Django 2.1.1 on 2018-12-11 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0028_auto_20181206_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingHoursRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.FloatField(default=0.0)),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('trainee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trainee', to='user_management.Member')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trainer', to='user_management.Member')),
            ],
        ),
    ]
