# Generated by Django 2.1.1 on 2018-12-14 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0047_auto_20181214_1012'),
        ('user_management', '0030_member_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='budget.Client'),
        ),
        migrations.AddField(
            model_name='incident',
            name='additional_comments',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='incident',
            name='client_at_risk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='client_aware',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='justification',
            field=models.CharField(default='', max_length=900),
        ),
        migrations.AddField(
            model_name='incident',
            name='platform',
            field=models.IntegerField(choices=[(0, 'Adwords'), (1, 'Facebook'), (2, 'Bing')], default=0),
        ),
        migrations.AddField(
            model_name='incident',
            name='refund_amount',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='incident',
            name='refund_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='incident',
            name='date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.CharField(default='', max_length=355),
        ),
    ]
