# Generated by Django 2.1.1 on 2019-01-04 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0031_auto_20181214_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.Client'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_by', to='user_management.Member'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_member', to='user_management.Member'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.BackupPeriod'),
        ),
        migrations.AlterField(
            model_name='backupperiod',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.Member'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.Client'),
        ),
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.RoleGroup'),
        ),
        migrations.AlterField(
            model_name='traininghoursrecord',
            name='trainee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainee', to='user_management.Member'),
        ),
        migrations.AlterField(
            model_name='traininghoursrecord',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer', to='user_management.Member'),
        ),
    ]
