# Generated by Django 2.1.1 on 2019-02-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0032_auto_20190104_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='deactivated',
            field=models.BooleanField(default=False),
        ),
    ]
