# Generated by Django 2.1.1 on 2019-03-01 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0033_member_deactivated'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='similar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similar_member', to='user_management.Member'),
        ),
    ]
