# Generated by Django 2.1.1 on 2019-03-08 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0035_auto_20190306_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backup',
            name='similar',
        ),
    ]
