# Generated by Django 2.1.1 on 2019-04-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0037_auto_20190415_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
