# Generated by Django 2.1.1 on 2019-04-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0038_auto_20190415_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.CharField(default='', max_length=900),
        ),
        migrations.AlterField(
            model_name='incident',
            name='service',
            field=models.IntegerField(choices=[(0, 'Paid Media'), (1, 'SEO'), (2, 'CRO'), (3, 'Client Services'), (4, 'Biz Dev'), (5, 'Internal Oops'), (6, 'None')], default=0),
        ),
    ]
