# Generated by Django 2.1.1 on 2019-04-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0039_auto_20190419_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='incident',
            name='justification',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
