# Generated by Django 2.1.1 on 2019-04-19 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0037_memberhourhistory'),
        ('user_management', '0040_auto_20190419_0841'),
    ]

    operations = [
    ]
