# Generated by Django 2.1.1 on 2019-04-30 18:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0042_highfive'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=355)),
            ],
        ),
        migrations.RemoveField(
            model_name='incident',
            name='issue_type',
        ),
        migrations.AddField(
            model_name='highfive',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='issue',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_management.IncidentReason'),
        ),
    ]
