# Generated by Django 2.1.1 on 2019-04-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0044_incident_reporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='addressed_with_member',
            field=models.BooleanField(default=False),
        ),
    ]
