# Generated by Django 2.1.1 on 2019-05-13 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0045_incident_addressed_with_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='highfive',
            name='nominator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominator', to='user_management.Member'),
        ),
        migrations.AlterField(
            model_name='highfive',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_member', to='user_management.Member'),
        ),
    ]
