# Generated by Django 2.1.1 on 2019-05-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0046_remove_incident_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='members',
            field=models.ManyToManyField(default=None, related_name='incident_members', to='user_management.Member'),
        ),
    ]
