# Generated by Django 2.1.1 on 2019-05-14 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0049_member_last_viewed_summary'),
        ('user_management', '0046_auto_20190513_0753'),
    ]

    operations = [
    ]
