# Generated by Django 2.1.1 on 2019-05-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0050_merge_20190514_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='refund_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
