# Generated by Django 2.1.1 on 2019-05-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0050_merge_20190514_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='platform',
            field=models.IntegerField(choices=[(0, 'Adwords'), (1, 'Facebook'), (2, 'Bing'), (3, 'Other'), (4, 'None')], default=0),
        ),
    ]
