# Generated by Django 2.1.1 on 2019-05-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0051_auto_20190524_0806'),
        ('user_management', '0051_incident_refund_amount'),
    ]

    operations = [
    ]
