# Generated by Django 2.1.1 on 2019-06-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0052_merge_20190529_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillentry',
            name='score',
            field=models.IntegerField(choices=[(0, 'Unscored'), (1, 'Terrible'), (2, 'Poor'), (3, 'Good'), (4, 'Excellent')], default=0),
        ),
    ]
