# Generated by Django 2.1.1 on 2019-06-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0053_auto_20190611_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
