# Generated by Django 2.1.1 on 2019-06-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0055_traininggroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininggroup',
            name='members',
            field=models.ManyToManyField(blank=True, default=None, to='user_management.Member'),
        ),
        migrations.AlterField(
            model_name='traininggroup',
            name='roles',
            field=models.ManyToManyField(blank=True, default=None, to='user_management.Role'),
        ),
        migrations.AlterField(
            model_name='traininggroup',
            name='skills',
            field=models.ManyToManyField(blank=True, default=None, to='user_management.Skill'),
        ),
    ]
