# Generated by Django 2.1.1 on 2019-06-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0056_auto_20190612_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininggroup',
            name='skill_entries',
            field=models.ManyToManyField(blank=True, default=None, to='user_management.SkillEntry'),
        ),
    ]
