# Generated by Django 2.1.1 on 2019-06-12 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0057_traininggroup_skill_entries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traininggroup',
            name='skill_entries',
        ),
    ]
