# Generated by Django 2.1.1 on 2019-06-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0058_remove_traininggroup_skill_entries'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='skillhistory',
            name='member',
        ),
        migrations.RemoveField(
            model_name='skillhistory',
            name='skill',
        ),
        migrations.DeleteModel(
            name='SkillHistory',
        ),
    ]
