# Generated by Django 2.1.1 on 2019-06-12 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0059_auto_20190612_1500'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SkillCategory',
        ),
    ]
