# Generated by Django 2.1.1 on 2019-06-14 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0060_delete_skillcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('skill_entry', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_management.SkillEntry')),
            ],
        ),
    ]
