# Generated by Django 2.1.1 on 2019-06-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0062_auto_20190617_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='members',
            field=models.ManyToManyField(to='user_management.Member'),
        ),
    ]
