# Generated by Django 2.1.1 on 2019-08-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0066_member_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='buffer_internal_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='buffer_learning_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='buffer_planning_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='buffer_sales_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='buffer_seniority_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='buffer_total_percentage',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='buffer_trainers_percentage',
            field=models.FloatField(default=0),
        ),
    ]
