# Generated by Django 2.1.1 on 2019-08-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0067_auto_20190814_0823'),
        ('user_management', '0067_auto_20190819_0929'),
    ]

    operations = [
    ]
