# Generated by Django 2.1.1 on 2019-08-21 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0069_auto_20190820_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.Member')),
                ('skill_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.SkillCategory')),
            ],
        ),
    ]
