# Generated by Django 2.1.1 on 2019-08-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0070_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(height_field=512, null=True, upload_to='bloomers/', width_field=512),
        ),
    ]
