# Generated by Django 2.1.1 on 2019-08-29 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0070_badge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='buffer_planning_percentage',
            new_name='buffer_other_percentage',
        ),
    ]
