# Generated by Django 2.1.1 on 2019-08-22 15:01

from django.db import migrations, models
import user_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0072_auto_20190822_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(null=True, upload_to=user_management.models.member_image_path),
        ),
    ]
