# Generated by Django 2.1.1 on 2019-08-29 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0071_auto_20190829_0711'),
        ('user_management', '0074_auto_20190827_0753'),
    ]

    operations = [
    ]
