# Generated by Django 2.1.1 on 2019-09-12 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0076_auto_20190910_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='buffer_learning_percentage',
        ),
    ]
