# Generated by Django 2.1.1 on 2019-09-17 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0094_merge_20190827_1420'),
        ('user_management', '0077_remove_member_buffer_learning_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.IntegerField(choices=[(0, 'Paid Media'), (1, 'SEO'), (2, 'CRO'), (3, 'Client Services'), (4, 'Biz Dev'), (5, 'Internal Oops'), (6, 'None')], default=0)),
                ('timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('description', models.CharField(default='', max_length=2000)),
                ('budget_error_amount', models.FloatField(default=0.0)),
                ('refund_amount', models.FloatField(default=0.0)),
                ('platform', models.IntegerField(choices=[(0, 'Adwords'), (1, 'Facebook'), (2, 'Bing'), (3, 'Other'), (4, 'None')], default=0)),
                ('client_aware', models.BooleanField(default=False)),
                ('client_at_risk', models.BooleanField(default=False)),
                ('addressed_with_member', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('justification', models.CharField(default='', max_length=2000)),
                ('account', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.Client')),
                ('issue', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_management.IncidentReason')),
                ('members', models.ManyToManyField(default=None, related_name='client_oops_members', to='user_management.Member')),
                ('reporter', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_oops_reporter', to='user_management.Member')),
            ],
        ),
        migrations.CreateModel(
            name='InternalOops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('description', models.CharField(default='', max_length=2000)),
                ('issue', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_management.IncidentReason')),
                ('members', models.ManyToManyField(default=None, related_name='internal_oops_members', to='user_management.Member')),
                ('reporter', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_oops_reporter', to='user_management.Member')),
            ],
        ),
        migrations.RemoveField(
            model_name='incident',
            name='account',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='members',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='reporter',
        ),
        migrations.DeleteModel(
            name='Incident',
        ),
    ]
