# Generated by Django 2.1.1 on 2019-09-17 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0077_remove_member_buffer_learning_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalOops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('description', models.CharField(default='', max_length=2000)),
                ('issue', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_management.IncidentReason')),
                ('members', models.ManyToManyField(default=None, related_name='internal_oops_members', to='user_management.Member')),
                ('reporter', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_oops_reporter', to='user_management.Member')),
            ],
        ),
        migrations.RemoveField(
            model_name='incident',
            name='approved',
        ),
        migrations.AlterField(
            model_name='incident',
            name='reporter',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_oops_reporter', to='user_management.Member'),
        ),
    ]
