# Generated by Django 2.1.1 on 2019-09-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0078_auto_20190917_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientoops',
            name='approved',
        ),
    ]
