# Generated by Django 2.1.1 on 2019-10-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0080_memberhourhistory_buffer_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberhourhistory',
            name='training_buffer',
            field=models.FloatField(default=0.0),
        ),
    ]
