# Generated by Django 2.1.1 on 2019-10-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0081_memberhourhistory_training_buffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberhourhistory',
            name='total_buffer',
            field=models.FloatField(default=0.0),
        ),
    ]
