# Generated by Django 2.1.1 on 2019-10-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0096_auto_20191010_1243'),
        ('user_management', '0083_auto_20191015_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberhourhistory',
            name='num_active_accounts',
        ),
        migrations.RemoveField(
            model_name='memberhourhistory',
            name='num_onboarding_accounts',
        ),
        migrations.AddField(
            model_name='memberhourhistory',
            name='active_accounts',
            field=models.ManyToManyField(blank=True, default=None, related_name='active_accounts', to='budget.Client'),
        ),
        migrations.AddField(
            model_name='memberhourhistory',
            name='backup_accounts',
            field=models.ManyToManyField(blank=True, default=None, related_name='backup_accounts', to='budget.Client'),
        ),
        migrations.AddField(
            model_name='memberhourhistory',
            name='onboarding_accounts',
            field=models.ManyToManyField(blank=True, default=None, related_name='onboarding_accounts', to='budget.Client'),
        ),
    ]
