# Generated by Django 2.1.1 on 2019-10-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0084_auto_20191015_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberhourhistory',
            name='active_accounts',
        ),
        migrations.RemoveField(
            model_name='memberhourhistory',
            name='backup_accounts',
        ),
        migrations.RemoveField(
            model_name='memberhourhistory',
            name='onboarding_accounts',
        ),
        migrations.AddField(
            model_name='memberhourhistory',
            name='backup_hours_plus_minus',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='memberhourhistory',
            name='num_active_accounts',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='memberhourhistory',
            name='num_onboarding_accounts',
            field=models.FloatField(default=0.0),
        ),
    ]
