# Generated by Django 2.1.1 on 2019-10-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0086_accountmemberhourhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmemberhourhistory',
            name='account',
        ),
        migrations.RemoveField(
            model_name='accountmemberhourhistory',
            name='member',
        ),
        migrations.DeleteModel(
            name='AccountMemberHourHistory',
        ),
    ]
