# Generated by Django 2.1.1 on 2019-10-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0097_merge_20191016_0843'),
        ('user_management', '0087_auto_20191024_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberDashboardSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1)),
                ('year', models.PositiveSmallIntegerField(blank=True, default=1999)),
                ('new_accounts', models.ManyToManyField(related_name='new_accounts', to='budget.Client')),
                ('outstanding_budget_accounts', models.ManyToManyField(related_name='outstanding_budget_accounts', to='budget.Client')),
            ],
        ),
    ]
