# Generated by Django 2.1.1 on 2019-10-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0088_memberdashboardsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdashboardsnapshot',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
