# Generated by Django 2.1.1 on 2019-10-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0089_memberdashboardsnapshot_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberdashboardsnapshot',
            name='outstanding_budget_accounts',
            field=models.ManyToManyField(related_name='outstanding_budget_accounts', to='client_area.ClientDashboardSnapshot'),
        ),
    ]
