# Generated by Django 2.1.1 on 2019-10-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0090_auto_20191024_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdashboardsnapshot',
            name='aggregate_fee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='memberdashboardsnapshot',
            name='aggregate_spend',
            field=models.FloatField(default=0.0),
        ),
    ]
