# Generated by Django 2.1.1 on 2019-11-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0092_memberhourhistory_seniority_buffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberdashboardsnapshot',
            name='outstanding_budget_accounts',
            field=models.ManyToManyField(related_name='outstanding_budget_accounts', to='budget.Client'),
        ),
    ]
