# Generated by Django 2.1.1 on 2019-11-12 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0093_auto_20191104_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberdashboardsnapshot',
            name='new_accounts',
        ),
        migrations.RemoveField(
            model_name='memberdashboardsnapshot',
            name='outstanding_budget_accounts',
        ),
    ]
