# Generated by Django 2.1.1 on 2019-11-12 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0095_auto_20191112_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberdashboardsnapshot',
            name='outstanding_budget_accounts',
        ),
    ]
