# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-18 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0005_clienttype_industry_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=255)),
                ('email', models.EmailField(default='None', max_length=255)),
            ],
        ),
    ]
