# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-18 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0006_clientcontact'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='memberclientrelationship',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='memberclientrelationship',
            name='client',
        ),
        migrations.RemoveField(
            model_name='memberclientrelationship',
            name='member',
        ),
        migrations.RemoveField(
            model_name='memberclientrelationship',
            name='relationship',
        ),
        migrations.DeleteModel(
            name='MemberClientRelationship',
        ),
        migrations.DeleteModel(
            name='MemberClientRelationshipType',
        ),
    ]
