# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-26 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0012_managementfeeinterval_managementfeesstructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontact',
            name='phone',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
