# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-16 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0014_managementfeesstructure_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounthourrecord',
            name='day',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
