# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-16 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0015_accounthourrecord_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounthourrecord',
            name='is_unpaid',
            field=models.BooleanField(default=False),
        ),
    ]
