# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-16 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0017_accounthourrecord_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounthourrecord',
            name='day',
        ),
    ]
