# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-23 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0033_auto_20181023_1426'),
        ('user_management', '0022_auto_20181001_1721'),
        ('client_area', '0018_remove_accounthourrecord_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1)),
                ('year', models.IntegerField(default=0)),
                ('tier', models.IntegerField(default=1)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('date_received_by_am', models.DateTimeField(blank=True, null=True)),
                ('date_sent_by_am', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.Client')),
                ('cm', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.Member')),
            ],
        ),
        migrations.AlterField(
            model_name='accountchanges',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.Client'),
        ),
        migrations.AlterField(
            model_name='accountchanges',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.Member'),
        ),
    ]
