# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-23 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0019_auto_20181023_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='report_services',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'PPC'), (2, 'SEO'), (3, 'Both')], default=0),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='report_type',
            field=models.IntegerField(choices=[(1, 'Standard'), (2, 'Advanced')], default=1),
        ),
    ]
