# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-24 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0020_auto_20181023_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyreport',
            old_name='date_received_by_am',
            new_name='date_sent_to_am',
        ),
    ]
