# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-07 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0038_auto_20181107_1435'),
        ('user_management', '0022_auto_20181001_1721'),
        ('client_area', '0023_promo_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAllocatedHoursHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('allocated_hours', models.FloatField(default=0)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.Client')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.Member')),
            ],
        ),
    ]
