# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-09 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0024_accountallocatedhourshistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='has_aw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promo',
            name='has_bing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promo',
            name='has_fb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promo',
            name='has_other',
            field=models.BooleanField(default=False),
        ),
    ]
