# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-09 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0025_auto_20181109_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='confirmed_ended',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='confirmed_started',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
