# Generated by Django 2.1.1 on 2018-11-12 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0026_auto_20181109_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounthourrecord',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='client', to='budget.Client'),
        ),
        migrations.AlterField(
            model_name='accounthourrecord',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='member', to='user_management.Member'),
        ),
    ]
