# Generated by Django 2.1.1 on 2018-12-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0027_auto_20181112_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='is_indefinite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='promo',
            name='end_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
