# Generated by Django 2.1.1 on 2019-01-04 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0028_auto_20181217_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounthourrecord',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to='budget.Client'),
        ),
        migrations.AlterField(
            model_name='accounthourrecord',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to='user_management.Member'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='is_indefinite',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
