# Generated by Django 2.1.1 on 2019-01-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0029_auto_20190104_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontact',
            name='email',
            field=models.EmailField(default='None', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='name',
            field=models.CharField(default='None', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='phone',
            field=models.CharField(default='None', max_length=255, null=True),
        ),
    ]
