# Generated by Django 2.1.1 on 2019-01-14 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0051_auto_20190108_0953'),
        ('client_area', '0031_onboardingtask_onboardingtaskassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.IntegerField(choices=[(0, 'PPC'), (1, 'SEO'), (2, 'CRO'), (3, 'Strategy')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingStepAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.Client')),
                ('step', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_area.OnboardingStep')),
            ],
        ),
        migrations.RemoveField(
            model_name='onboardingtask',
            name='service',
        ),
        migrations.RemoveField(
            model_name='onboardingtaskassignment',
            name='account',
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='step',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_area.OnboardingStep'),
        ),
        migrations.AddField(
            model_name='onboardingtaskassignment',
            name='step',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_area.OnboardingStepAssignment'),
        ),
    ]
