# Generated by Django 2.1.1 on 2019-01-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0033_onboardingstep_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingtaskassignment',
            name='completed',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
