# Generated by Django 2.1.1 on 2019-01-28 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0056_auto_20190128_0956'),
        ('user_management', '0032_auto_20190104_0950'),
        ('client_area', '0035_auto_20190123_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('phase', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three')], default=1)),
                ('tier', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three')], default=1)),
                ('day', models.IntegerField(default=1)),
                ('roles', models.ManyToManyField(blank=True, default=None, to='user_management.Role')),
            ],
        ),
        migrations.CreateModel(
            name='PhaseTaskAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.Client')),
                ('task', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_area.PhaseTask')),
            ],
        ),
    ]
