# Generated by Django 2.1.1 on 2019-01-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0036_phasetask_phasetaskassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='phasetaskassignment',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phasetaskassignment',
            name='completed',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
