# Generated by Django 2.1.1 on 2019-01-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0037_auto_20190128_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='phasetaskassignment',
            name='bc_link',
            field=models.CharField(blank=True, max_length=355),
        ),
    ]
