# Generated by Django 2.1.1 on 2019-01-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0038_phasetaskassignment_bc_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phasetaskassignment',
            name='bc_link',
            field=models.CharField(blank=True, default=None, max_length=355, null=True),
        ),
    ]
