# Generated by Django 2.1.1 on 2019-02-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0039_auto_20190130_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='no_report',
            field=models.BooleanField(default=False),
        ),
    ]
