# Generated by Django 2.1.1 on 2019-02-18 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0059_client_budget_updated'),
        ('client_area', '0040_monthlyreport_no_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifecycleEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=240)),
                ('phase', models.IntegerField(default=1)),
                ('phase_day', models.IntegerField(default=1)),
                ('cycle', models.IntegerField(default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.Client')),
                ('related_task', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_area.PhaseTaskAssignment')),
            ],
        ),
    ]
