# Generated by Django 2.1.1 on 2019-02-19 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0041_lifecycleevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifecycleevent',
            name='related_task',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_area.PhaseTaskAssignment'),
        ),
    ]
