# Generated by Django 2.1.1 on 2019-02-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0042_auto_20190219_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifecycleevent',
            name='type',
            field=models.IntegerField(choices=[(1, 'Account flagged'), (2, 'Upsell attempt'), (3, 'Other ')], default=0),
        ),
    ]
