# Generated by Django 2.1.1 on 2019-02-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0043_lifecycleevent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifecycleevent',
            name='type',
            field=models.IntegerField(choices=[(1, 'Account won'), (2, 'Onboarding complete'), (3, 'Account inactive'), (4, 'Account active'), (5, 'Account lost'), (6, 'Upsell attempt'), (7, '90 days task complete'), (8, 'Account flagged'), (9, 'Other ')], default=1),
        ),
    ]
