# Generated by Django 2.1.1 on 2019-02-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0032_auto_20190104_0950'),
        ('client_area', '0044_auto_20190219_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifecycleevent',
            name='adwords_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lifecycleevent',
            name='bing_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lifecycleevent',
            name='cro_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lifecycleevent',
            name='facebook_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lifecycleevent',
            name='members',
            field=models.ManyToManyField(blank=True, to='user_management.Member'),
        ),
        migrations.AddField(
            model_name='lifecycleevent',
            name='monthly_budget',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='lifecycleevent',
            name='seo_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lifecycleevent',
            name='spend',
            field=models.FloatField(default=0.0),
        ),
    ]
