# Generated by Django 2.1.1 on 2019-02-20 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0032_auto_20190104_0950'),
        ('client_area', '0045_auto_20190219_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='phasetaskassignment',
            name='completed_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.Member'),
        ),
        migrations.AlterField(
            model_name='lifecycleevent',
            name='type',
            field=models.IntegerField(choices=[(1, 'Account won'), (2, 'Onboarding complete'), (3, 'Account inactive'), (4, 'Account active'), (5, 'Account lost'), (6, 'Upsell attempt'), (7, '90 days task complete'), (8, 'Account flagged'), (9, 'Other '), (10, 'Member assigned to flagged account')], default=1),
        ),
    ]
