# Generated by Django 2.1.1 on 2019-02-22 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0047_auto_20190221_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phasetaskassignment',
            name='completed_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.Member'),
        ),
    ]
