# Generated by Django 2.1.1 on 2019-02-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0048_auto_20190222_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='phasetaskassignment',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
