# Generated by Django 2.1.1 on 2019-02-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0033_member_deactivated'),
        ('client_area', '0049_phasetaskassignment_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='phasetask',
            name='members',
            field=models.ManyToManyField(blank=True, default=None, to='user_management.Member'),
        ),
    ]
