# Generated by Django 2.1.1 on 2019-02-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0050_phasetask_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='phasetaskassignment',
            name='cycle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phasetaskassignment',
            name='phase',
            field=models.IntegerField(default=0),
        ),
    ]
