# Generated by Django 2.1.1 on 2019-03-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0051_auto_20190227_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='confirmed_ended',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='confirmed_started',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='desc',
            field=models.CharField(blank=True, default='No description', max_length=140, null=True),
        ),
    ]
