# Generated by Django 2.1.1 on 2019-03-15 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0053_upsellattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifecycleevent',
            name='related_upsett',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_area.UpsellAttempt'),
        ),
        migrations.AlterField(
            model_name='upsellattempt',
            name='service',
            field=models.IntegerField(choices=[(1, 'PPC'), (2, 'SEO'), (3, 'CRO'), (4, 'Strategy'), (5, 'Feed Management'), (6, 'Email Marketing')], default=1),
        ),
    ]
