# Generated by Django 2.1.1 on 2019-03-15 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0054_auto_20190315_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lifecycleevent',
            old_name='related_upsett',
            new_name='related_upsell',
        ),
    ]
