# Generated by Django 2.1.1 on 2019-03-21 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0036_remove_backup_similar'),
        ('client_area', '0056_salesprofile_salesprofilechange'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesprofilechange',
            name='member',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.Member'),
        ),
        migrations.AlterField(
            model_name='salesprofile',
            name='cro_status',
            field=models.IntegerField(choices=[(0, 'Onboarding'), (1, 'Active'), (2, 'Inactive'), (3, 'Lost'), (4, 'Opportunity'), (5, 'Pitched'), (6, 'None')], default=6),
        ),
        migrations.AlterField(
            model_name='salesprofile',
            name='email_status',
            field=models.IntegerField(choices=[(0, 'Onboarding'), (1, 'Active'), (2, 'Inactive'), (3, 'Lost'), (4, 'Opportunity'), (5, 'Pitched'), (6, 'None')], default=6),
        ),
        migrations.AlterField(
            model_name='salesprofile',
            name='feed_status',
            field=models.IntegerField(choices=[(0, 'Onboarding'), (1, 'Active'), (2, 'Inactive'), (3, 'Lost'), (4, 'Opportunity'), (5, 'Pitched'), (6, 'None')], default=6),
        ),
        migrations.AlterField(
            model_name='salesprofile',
            name='ppc_status',
            field=models.IntegerField(choices=[(0, 'Onboarding'), (1, 'Active'), (2, 'Inactive'), (3, 'Lost'), (4, 'Opportunity'), (5, 'Pitched'), (6, 'None')], default=6),
        ),
        migrations.AlterField(
            model_name='salesprofile',
            name='seo_status',
            field=models.IntegerField(choices=[(0, 'Onboarding'), (1, 'Active'), (2, 'Inactive'), (3, 'Lost'), (4, 'Opportunity'), (5, 'Pitched'), (6, 'None')], default=6),
        ),
        migrations.AlterField(
            model_name='salesprofile',
            name='strat_status',
            field=models.IntegerField(choices=[(0, 'Onboarding'), (1, 'Active'), (2, 'Inactive'), (3, 'Lost'), (4, 'Opportunity'), (5, 'Pitched'), (6, 'None')], default=6),
        ),
        migrations.AlterField(
            model_name='salesprofilechange',
            name='from_status',
            field=models.IntegerField(choices=[(0, 'Onboarding'), (1, 'Active'), (2, 'Inactive'), (3, 'Lost'), (4, 'Opportunity'), (5, 'Pitched'), (6, 'None')], default=0),
        ),
        migrations.AlterField(
            model_name='salesprofilechange',
            name='to_status',
            field=models.IntegerField(choices=[(0, 'Onboarding'), (1, 'Active'), (2, 'Inactive'), (3, 'Lost'), (4, 'Opportunity'), (5, 'Pitched'), (6, 'None')], default=0),
        ),
    ]
