# Generated by Django 2.1.1 on 2019-03-26 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0058_opportunitydescription_pitcheddescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesprofile',
            name='cro_opp_desc',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cro_opp', to='client_area.OpportunityDescription'),
        ),
        migrations.AddField(
            model_name='salesprofile',
            name='cro_pithced_desc',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cro_pitch', to='client_area.PitchedDescription'),
        ),
        migrations.AddField(
            model_name='salesprofile',
            name='email_opp_desc',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_opp', to='client_area.OpportunityDescription'),
        ),
        migrations.AddField(
            model_name='salesprofile',
            name='email_pithced_desc',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_opp', to='client_area.PitchedDescription'),
        ),
        migrations.AddField(
            model_name='salesprofile',
            name='feed_opp_desc',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_opp', to='client_area.OpportunityDescription'),
        ),
        migrations.AddField(
            model_name='salesprofile',
            name='feed_pithced_desc',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_opp', to='client_area.PitchedDescription'),
        ),
        migrations.AddField(
            model_name='salesprofile',
            name='ppc_opp_desc',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ppc_opp', to='client_area.OpportunityDescription'),
        ),
        migrations.AddField(
            model_name='salesprofile',
            name='ppc_pithced_desc',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ppc_pitch', to='client_area.PitchedDescription'),
        ),
        migrations.AddField(
            model_name='salesprofile',
            name='seo_opp_desc',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo_opp', to='client_area.OpportunityDescription'),
        ),
        migrations.AddField(
            model_name='salesprofile',
            name='seo_pithced_desc',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo_pitch', to='client_area.PitchedDescription'),
        ),
        migrations.AddField(
            model_name='salesprofile',
            name='strat_opp_desc',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strat_opp', to='client_area.OpportunityDescription'),
        ),
        migrations.AddField(
            model_name='salesprofile',
            name='strat_pithced_desc',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strat_opp', to='client_area.PitchedDescription'),
        ),
    ]
