# Generated by Django 2.1.1 on 2019-03-26 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0059_auto_20190326_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesprofilechange',
            name='opp_desc',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_area.OpportunityDescription'),
        ),
        migrations.AddField(
            model_name='salesprofilechange',
            name='pithced_desc',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_area.PitchedDescription'),
        ),
    ]
