# Generated by Django 2.1.1 on 2019-03-27 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0060_auto_20190326_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesprofile',
            old_name='cro_pithced_desc',
            new_name='cro_pitched_desc',
        ),
        migrations.RenameField(
            model_name='salesprofile',
            old_name='email_pithced_desc',
            new_name='email_pitched_desc',
        ),
        migrations.RenameField(
            model_name='salesprofile',
            old_name='feed_pithced_desc',
            new_name='feed_pitched_desc',
        ),
        migrations.RenameField(
            model_name='salesprofile',
            old_name='ppc_pithced_desc',
            new_name='ppc_pitched_desc',
        ),
        migrations.RenameField(
            model_name='salesprofile',
            old_name='seo_pithced_desc',
            new_name='seo_pitched_desc',
        ),
        migrations.RenameField(
            model_name='salesprofile',
            old_name='strat_pithced_desc',
            new_name='strat_pitched_desc',
        ),
    ]
