# Generated by Django 2.1.1 on 2019-03-27 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0061_auto_20190327_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesprofilechange',
            old_name='pithced_desc',
            new_name='pitched_desc',
        ),
    ]
