# Generated by Django 2.1.1 on 2019-04-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0062_auto_20190327_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='MandateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
