# Generated by Django 2.1.1 on 2019-04-17 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0064_mandate'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandate',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mandate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mandate',
            name='end_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mandate',
            name='hourly_rate',
            field=models.FloatField(default=125.0),
        ),
        migrations.AddField(
            model_name='mandate',
            name='start_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
