# Generated by Django 2.1.1 on 2019-04-19 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0037_memberhourhistory'),
        ('client_area', '0067_mandatetype_hourly_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MandateAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(default=0.0)),
                ('mandate', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_area.Mandate')),
                ('member', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.Member')),
            ],
        ),
        migrations.CreateModel(
            name='MandateHourRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.FloatField(default=0.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_area.MandateAssignment')),
            ],
        ),
    ]
