# Generated by Django 2.1.1 on 2019-04-19 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0068_mandateassignment_mandatehourrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandate',
            name='members',
        ),
    ]
