# Generated by Django 2.1.1 on 2019-04-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0069_remove_mandate_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandatehourrecord',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=0.0),
        ),
        migrations.AddField(
            model_name='mandatehourrecord',
            name='year',
            field=models.IntegerField(default=1990),
        ),
    ]
