# Generated by Django 2.1.1 on 2019-05-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0070_auto_20190424_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandate',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
