# Generated by Django 2.1.1 on 2019-05-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0071_mandate_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandate',
            name='billing_style',
            field=models.IntegerField(choices=[(0, 'Hours'), (1, 'Fee')], default=0),
        ),
        migrations.AddField(
            model_name='mandate',
            name='ongoing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mandate',
            name='ongoing_cost',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mandate',
            name='ongoing_hours',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='cost',
            field=models.FloatField(default=None, null=True),
        ),
    ]
