# Generated by Django 2.1.1 on 2019-06-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0072_auto_20190529_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='includes_string',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='promo',
            name='label',
            field=models.CharField(default='', max_length=140),
        ),
    ]
