# Generated by Django 2.1.1 on 2019-06-04 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0073_auto_20190603_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsOnInPromo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aw_on', models.IntegerField(default=0)),
                ('aw_off', models.IntegerField(default=0)),
                ('fb_on', models.IntegerField(default=0)),
                ('fb_off', models.IntegerField(default=0)),
                ('bing_on', models.IntegerField(default=0)),
                ('bing_off', models.IntegerField(default=0)),
                ('promo', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_area.Promo')),
            ],
        ),
    ]
