# Generated by Django 2.1.1 on 2019-06-04 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0074_adsoninpromo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdsOnInPromo',
            new_name='AdsInPromo',
        ),
    ]
