# Generated by Django 2.1.1 on 2019-06-10 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0065_accountbudgetspendhistory_status'),
        ('client_area', '0075_auto_20190604_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('primary_service', models.IntegerField(choices=[(1, 'PPC'), (2, 'SEO'), (3, 'CRO')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.Client')),
                ('additional_service', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_area.MandateType')),
            ],
        ),
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='salesprofile',
            name='cro_opp_desc',
        ),
        migrations.RemoveField(
            model_name='salesprofile',
            name='cro_pitched_desc',
        ),
        migrations.RemoveField(
            model_name='salesprofile',
            name='email_opp_desc',
        ),
        migrations.RemoveField(
            model_name='salesprofile',
            name='email_pitched_desc',
        ),
        migrations.RemoveField(
            model_name='salesprofile',
            name='email_status',
        ),
        migrations.RemoveField(
            model_name='salesprofile',
            name='feed_opp_desc',
        ),
        migrations.RemoveField(
            model_name='salesprofile',
            name='feed_pitched_desc',
        ),
        migrations.RemoveField(
            model_name='salesprofile',
            name='feed_status',
        ),
        migrations.RemoveField(
            model_name='salesprofile',
            name='ppc_opp_desc',
        ),
        migrations.RemoveField(
            model_name='salesprofile',
            name='ppc_pitched_desc',
        ),
        migrations.RemoveField(
            model_name='salesprofile',
            name='seo_opp_desc',
        ),
        migrations.RemoveField(
            model_name='salesprofile',
            name='seo_pitched_desc',
        ),
        migrations.RemoveField(
            model_name='salesprofile',
            name='strat_opp_desc',
        ),
        migrations.RemoveField(
            model_name='salesprofile',
            name='strat_pitched_desc',
        ),
        migrations.RemoveField(
            model_name='salesprofile',
            name='strat_status',
        ),
    ]
