# Generated by Django 2.1.1 on 2019-06-10 19:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0065_accountbudgetspendhistory_status'),
        ('client_area', '0076_auto_20190610_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='reason',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_area.OpportunityDescription'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='account',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.Client'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='additional_service',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_area.MandateType'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pitch',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pitch',
            name='primary_service',
            field=models.IntegerField(choices=[(1, 'PPC'), (2, 'SEO'), (3, 'CRO')], default=0),
        ),
        migrations.AddField(
            model_name='pitch',
            name='reason',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_area.PitchedDescription'),
        ),
    ]
