# Generated by Django 2.1.1 on 2019-06-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0077_auto_20190610_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesprofile',
            name='cro_status',
            field=models.IntegerField(choices=[(0, 'Onboarding'), (1, 'Active'), (2, 'Inactive'), (3, 'Lost'), (6, 'None')], default=6),
        ),
        migrations.AlterField(
            model_name='salesprofile',
            name='ppc_status',
            field=models.IntegerField(choices=[(0, 'Onboarding'), (1, 'Active'), (2, 'Inactive'), (3, 'Lost'), (6, 'None')], default=6),
        ),
        migrations.AlterField(
            model_name='salesprofile',
            name='seo_status',
            field=models.IntegerField(choices=[(0, 'Onboarding'), (1, 'Active'), (2, 'Inactive'), (3, 'Lost'), (6, 'None')], default=6),
        ),
    ]
