# Generated by Django 2.1.1 on 2019-06-11 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0078_auto_20190611_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='opportunity',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_area.Opportunity'),
        ),
    ]
