# Generated by Django 2.1.1 on 2019-06-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0081_auto_20190621_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='includes_string',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='promo',
            name='label',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
    ]
