# Generated by Django 2.1.1 on 2019-08-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0084_opportunity_flagged_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='status',
            field=models.IntegerField(choices=[(0, 'Flagged'), (1, 'In Progress'), (2, 'Lost'), (3, 'Won')], default=0),
        ),
    ]
