# Generated by Django 2.1.1 on 2019-08-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0086_opportunity_lost_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingstepassignment',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboardingstepassignment',
            name='completed',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
