# Generated by Django 2.1.1 on 2019-08-15 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0087_auto_20190815_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingstep',
            name='service',
        ),
    ]
