# Generated by Django 2.1.1 on 2019-08-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0088_remove_onboardingstep_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontact',
            name='email',
            field=models.EmailField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='name',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='phone',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
