# Generated by Django 2.1.1 on 2019-08-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0089_auto_20190821_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontact',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='phone',
            field=models.CharField(default='', max_length=255),
        ),
    ]
