# Generated by Django 2.1.1 on 2019-10-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0090_auto_20190822_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='date_status',
            field=models.IntegerField(choices=[(0, 'Client Requested Due Date'), (1, 'Flexible')], default=None, null=True),
        ),
    ]
