# Generated by Django 2.1.1 on 2019-10-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0089_memberdashboardsnapshot_date_created'),
        ('client_area', '0092_accountallocatedhourshistory_worked_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDashboardSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1)),
                ('year', models.PositiveSmallIntegerField(blank=True, default=1999)),
                ('num_days_onboarding', models.IntegerField(default=None, null=True)),
                ('num_times_flagged', models.IntegerField(default=0)),
                ('tier', models.IntegerField(default=1)),
                ('client_name', models.CharField(default='None', max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(to='user_management.Member')),
            ],
        ),
    ]
