# Generated by Django 2.1.1 on 2019-10-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0093_clientdashboardsnapshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientdashboardsnapshot',
            old_name='members',
            new_name='assigned_members_array',
        ),
        migrations.AddField(
            model_name='clientdashboardsnapshot',
            name='account_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
