# Generated by Django 2.1.1 on 2019-10-31 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0097_merge_20191016_0843'),
        ('client_area', '0094_auto_20191024_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SEOServiceAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('account', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.Client')),
                ('service', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_area.SEOService')),
            ],
        ),
    ]
