# Generated by Django 2.1.1 on 2019-11-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_area', '0095_seoservice_seoserviceassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdashboardsnapshot',
            name='cro_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='clientdashboardsnapshot',
            name='has_cro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientdashboardsnapshot',
            name='has_seo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientdashboardsnapshot',
            name='seo_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
