version: '3'
networks:
  broker-net:
services:
  broker:
    hostname: rabbit1
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=bloom
      - RABBITMQ_DEFAULT_PASS=bloombrokerpass
      - RABBITMQ_DEFAULT_VHOST=celeryhost

    networks:
      - broker-net
    ports:
      - "5672:5672"

  worker:
    image: hyperdigitalteam/bloom
    working_dir: /bloom
    entrypoint: "sh /bloom/.deploy/docker-entrypoint.sh celery prod"
    links:
      - broker
    depends_on:
      - broker
    networks:
      - broker-net
    environment:
      - CQLENG_ALLOW_SCHEMA_MANAGEMENT=1
      - PSQL_NAME=bloom
      - PSQL_USER=bloom
      - PSQL_PASSWORD=Digital987x123
      - PSQL_HOST=bloom-database

  web:
    image: hyperdigitalteam/bloom
    working_dir: /bloom
    entrypoint: "sh /bloom/.deploy/docker-entrypoint.sh web prod"
    links:
      - worker
      - broker
    depends_on:
      - worker
      - broker
    networks:
      - broker-net
    ports:
      - "8000:8000"
    environment:
      - CQLENG_ALLOW_SCHEMA_MANAGEMENT=1
      - PSQL_NAME=bloom
      - PSQL_USER=bloom
      - PSQL_PASSWORD=Digital987x123
      - PSQL_HOST=bloom-database
