version: '3'
networks:
  app-net: 
    driver: bridge
  broker-net:
volumes:
  psql-data:  
services:
  broker:
    hostname: rabbit1
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=bloom
      - RABBITMQ_DEFAULT_PASS=bloombrokerpass
      - RABBITMQ_DEFAULT_VHOST=celeryhost

    networks:
      - broker-net
    ports:
      - "5672:5672"
  
  worker:
    image: hyperdigitalteam/bloom
    working_dir: /bloom
    entrypoint: "sh /bloom/.deploy/docker-entrypoint.sh celery prod"
    volumes:
      - .:/bloom
    links:
      - broker
      - psql
    depends_on:
      - broker
      - psql
    networks:
      - broker-net
      - app-net
    environment:
      - CQLENG_ALLOW_SCHEMA_MANAGEMENT=1

  web:
    image: hyperdigitalteam/bloom
    working_dir: /bloom
    entrypoint: "sh /bloom/.deploy/docker-entrypoint.sh web prod"
    volumes:
      - .:/bloom
    links:
      - worker
      - broker
      - psql
    depends_on:
      - worker
      - broker
      - psql
    networks:
      - broker-net
      - app-net
    ports:
      - "8000:8000"
  
  psql:
    image: 'postgres'
    volumes:
      - psql-data
    networks:
      - app-net
