# Generated by Django 2.1.1 on 2019-07-10 17:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0078_auto_20190709_0652'),
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAnalyticsReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(default='', max_length=99999)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=999)),
                ('report', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insights.GoogleAnalyticsReport')),
            ],
        ),
        migrations.AddField(
            model_name='googleanalyticsauth',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
