# Generated by Django 2.1.1 on 2019-07-10 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0078_auto_20190709_0652'),
        ('insights', '0002_auto_20190710_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAnalyticsAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ga_account_id', models.CharField(max_length=30)),
                ('account', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.Client')),
            ],
        ),
    ]
