# Generated by Django 2.1.1 on 2019-07-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0003_googleanalyticsaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleanalyticsaccount',
            name='ga_account_view',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='googleanalyticsaccount',
            name='ga_account_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
