# Generated by Django 2.1.1 on 2019-08-07 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0088_auto_20190805_1517'),
        ('insights', '0004_auto_20190710_1510'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoogleAnalyticsAccount',
            new_name='GoogleAnalyticsView',
        ),
    ]
