# Generated by Django 2.1.1 on 2019-08-15 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0090_budget_is_default'),
        ('insights', '0008_auto_20190807_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.Client')),
                ('ga_view', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insights.GoogleAnalyticsView')),
            ],
        ),
    ]
