# Generated by Django 2.1.1 on 2019-09-20 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bing_dashboard', '0020_auto_20190919_1346'),
        ('facebook_dashboard', '0020_auto_20190919_1346'),
        ('adwords_dashboard', '0026_auto_20190919_1346'),
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcheck',
            name='ad_network',
            field=models.IntegerField(choices=[(0, 'Google Ads'), (1, 'Facebook'), (2, 'Bing')], default=0),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='aw_account',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='adwords_dashboard.DependentAccount'),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='bing_account',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bing_dashboard.BingAccounts'),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='fb_account',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facebook_dashboard.FacebookAccount'),
        ),
    ]
