# Generated by Django 2.1.1 on 2019-09-20 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adwords_dashboard', '0026_auto_20190919_1346'),
        ('budget', '0094_merge_20190827_1420'),
        ('monitor', '0002_auto_20190920_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadSubstring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleAdsBadURLCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Bad'), (1, 'Good')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleAdsHealthcheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.Client')),
                ('aw_account', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='adwords_dashboard.DependentAccount')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleBadSubstringCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Bad'), (1, 'Good')], default=1)),
                ('healthcheck', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.GoogleAdsHealthcheck')),
            ],
        ),
        migrations.RemoveField(
            model_name='healthcheck',
            name='account',
        ),
        migrations.RemoveField(
            model_name='healthcheck',
            name='aw_account',
        ),
        migrations.RemoveField(
            model_name='healthcheck',
            name='bing_account',
        ),
        migrations.RemoveField(
            model_name='healthcheck',
            name='fb_account',
        ),
        migrations.DeleteModel(
            name='Healthcheck',
        ),
        migrations.AddField(
            model_name='googleadsbadurlcheck',
            name='healthcheck',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.GoogleAdsHealthcheck'),
        ),
    ]
