# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-30 13:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adwords_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependentaccount',
            name='ext_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='dependentaccount',
            name='ext_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dependentaccount',
            name='nlc_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='dependentaccount',
            name='nlc_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dependentaccount',
            name='wspend_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='dependentaccount',
            name='wspend_score',
            field=models.FloatField(default=0),
        ),
    ]
