# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-20 12:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adwords_dashboard', '0002_auto_20180830_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependentaccount',
            name='currency',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='dependentaccount',
            name='kw_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='dependentaccount',
            name='kw_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dependentaccount',
            name='sq_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='dependentaccount',
            name='sq_score',
            field=models.FloatField(default=0),
        ),
    ]
