# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-02 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adwords_dashboard', '0003_auto_20180920_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependentaccount',
            name='ch_flag',
            field=models.BooleanField(default=False),
        ),
    ]
