# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-31 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adwords_dashboard', '0005_campaign_campaign_yesterday_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependentaccount',
            name='desired_spend_end_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='dependentaccount',
            name='desired_spend_start_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
