# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-07 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adwords_dashboard', '0006_auto_20181031_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependentaccount',
            name='desired_spend_end_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dependentaccount',
            name='desired_spend_start_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
