# Generated by Django 2.1.1 on 2019-05-01 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adwords_dashboard', '0009_auto_20190104_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAdsAccountMonthRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=1970)),
                ('spend', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adwords_dashboard.DependentAccount')),
            ],
        ),
    ]
