# Generated by Django 2.1.1 on 2019-05-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adwords_dashboard', '0010_googleadsaccountmonthrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependentaccount',
            name='blacklisted',
            field=models.BooleanField(default=True),
        ),
    ]
