# Generated by Django 2.1.1 on 2019-06-04 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adwords_dashboard', '0011_auto_20190530_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('date_found_on', models.DateTimeField()),
                ('ad_group', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='adwords_dashboard.Adgroup')),
                ('campaign', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='adwords_dashboard.Campaign')),
            ],
        ),
    ]
