# Generated by Django 2.1.1 on 2019-06-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adwords_dashboard', '0013_badadalert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampaignStat',
        ),
    ]
