# Generated by Django 2.1.1 on 2019-06-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adwords_dashboard', '0014_delete_campaignstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='master_exclusion',
            field=models.BooleanField(default=False),
        ),
    ]
