# Generated by Django 2.1.1 on 2019-06-26 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adwords_dashboard', '0020_auto_20190626_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='master_exclusion',
        ),
    ]
