# Generated by Django 2.1.1 on 2019-07-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adwords_dashboard', '0021_remove_campaign_master_exclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
