# Generated by Django 2.1.1 on 2019-07-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adwords_dashboard', '0022_campaign_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignspenddaterange',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
