# Generated by Django 2.1.1 on 2019-09-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adwords_dashboard', '0025_auto_20190904_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_id',
            field=models.CharField(default='None', max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='campaign',
            unique_together=set(),
        ),
    ]
