# Generated by Django 2.1.1 on 2018-11-12 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0040_auto_20181112_1431'),
        ('user_management', '0024_auto_20181112_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=999)),
                ('link', models.URLField(max_length=499)),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='budget.Client')),
                ('member', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_management.Member')),
            ],
        ),
]
