# Generated by Django 2.1.1 on 2018-11-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20181114_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Client related'), (2, 'Internal Request'), (3, 'Monthly Reminder'), (4, 'Reporting'), (5, 'Other')], default=5),
        ),
    ]
