# Generated by Django 2.1.1 on 2018-11-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20181115_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='severity',
            field=models.IntegerField(blank=True, choices=[(0, 'Info'), (1, 'Reminder'), (2, 'Success'), (3, 'Warning'), (4, 'Urgent')], default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'Client related'), (1, 'Internal Request'), (2, 'Monthly Reminder'), (3, 'Reporting'), (4, 'Other')], default=4),
        ),
    ]
