# Generated by Django 2.1.1 on 2019-01-04 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_auto_20181213_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.Client'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='member',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.Member'),
        ),
    ]
