# Generated by Django 2.1.1 on 2019-06-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
