# Generated by Django 2.1.1 on 2019-06-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_todo_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='link',
            field=models.CharField(max_length=255),
        ),
    ]
