# Generated by Django 2.1.1 on 2019-06-10 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_auto_20190610_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='link',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='todo',
            name='member',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='user_management.Member'),
        ),
    ]
