# Generated by Django 2.1.1 on 2019-06-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0015_auto_20190610_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='type',
            field=models.IntegerField(choices=[(0, 'Promo'), (1, 'Notification'), (2, 'Phase Task'), (3, 'Change History')], default=None, null=True),
        ),
    ]
