# Generated by Django 2.1.1 on 2019-06-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0016_todo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='type',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'Promo'), (2, 'Notification'), (3, 'Phase Task'), (4, 'Change History')], default=0, null=True),
        ),
    ]
