# Generated by Django 2.1.1 on 2019-06-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0019_todo_phase_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='phase_task_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
