# Generated by Django 2.1.1 on 2019-06-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0020_auto_20190611_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'Other'), (1, 'Promo'), (2, 'Notification'), (3, 'Client Review'), (4, 'Change History')], default=0),
        ),
    ]
