# Generated by Django 2.1.1 on 2019-08-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0021_auto_20190621_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'Other'), (1, 'Promo'), (2, 'Notification'), (3, 'Client Review'), (4, 'Change History'), (5, 'Performance')], default=0),
        ),
    ]
