# Generated by Django 2.1.1 on 2019-08-29 14:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0023_sentemailrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemailrecord',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentemailrecord',
            name='month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sentemailrecord',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
