# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-25 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bing_dashboard', '0003_auto_20180920_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingcampaign',
            name='campaign_yesterday_cost',
            field=models.FloatField(default=0),
        ),
    ]
