# Generated by Django 2.1.1 on 2019-06-20 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bing_dashboard', '0009_bingcampaign_master_exclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='BingCampaignSpendDateRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spend', models.FloatField(default=0.0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('campaign', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bing_dashboard.BingCampaign')),
            ],
        ),
    ]
