# Generated by Django 2.1.1 on 2019-06-25 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bing_dashboard', '0010_bingcampaignspenddaterange'),
    ]

    operations = [
        migrations.CreateModel(
            name='BingCampaignExclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bing_dashboard.BingCampaign')),
            ],
        ),
    ]
