# Generated by Django 2.1.1 on 2019-06-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bing_dashboard', '0011_bingcampaignexclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingcampaign',
            name='spend_until_yesterday',
            field=models.FloatField(default=0.0),
        ),
    ]
