# Generated by Django 2.1.1 on 2019-06-26 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bing_dashboard', '0013_bingcampaignspenddaterange_spend_until_yesterday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bingcampaignexclusion',
            name='campaign',
        ),
        migrations.DeleteModel(
            name='BingCampaignExclusion',
        ),
    ]
