# Generated by Django 2.1.1 on 2019-06-26 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bing_dashboard', '0014_auto_20190626_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bingcampaign',
            name='master_exclusion',
        ),
    ]
