# Generated by Django 2.1.1 on 2019-07-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bing_dashboard', '0016_bingcampaign_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingcampaignspenddaterange',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
