# Generated by Django 2.1.1 on 2019-09-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bing_dashboard', '0019_auto_20190904_0848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='binganomalies',
            options={},
        ),
        migrations.AlterField(
            model_name='binganomalies',
            name='campaign_id',
            field=models.CharField(default='None', max_length=255, unique=True),
        ),
    ]
