# Generated by Django 2.1.1 on 2019-09-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bing_dashboard', '0020_auto_20190919_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingcampaign',
            name='campaign_id',
            field=models.CharField(default='None', max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='bingcampaign',
            unique_together=set(),
        ),
    ]
